# mocha searches for mocha.toml in the following locations, in order of priority:
#   - $MOCHA_DIR/mocha.toml
#   - $APPDATA/mocha/mocha.toml
#   - $XDG_CONFIG_HOME/mocha/mocha.toml
#   - $USERPROFILE/.config/mocha/mocha.toml

[cat]
# whether to include deprecated packages in cat result
# by default, not included
include-deprecated = false

# command which is run to show a manifest, where [path] is replaced by manifest path
# e.g. "bat [path]". by default simply prints to console.
command = ""