# mocha searches for mocha.toml in the following locations, in order of priority:
#   - $MOCHA_DIR/mocha.toml
#   - $APPDATA/mocha/mocha.toml
#   - $XDG_CONFIG_HOME/mocha/mocha.toml
#   - $USERPROFILE/.config/mocha/mocha.toml

[cat]
include-deprecated = false
command = ""

[colors]
accent = "purple"
error = "red"
warning = "yellow"
info = "blue"
